#!/usr/bin/env bash
# Install midnight study-room booking LaunchAgent (Mon–Fri targets, 3 days ahead).
# Fires Fri–Tue right after midnight (when LibCal opens +3 days) with small jitter.
# Prefers 360H, rotates 3 accounts for 12pm–10pm, then scrapes Outlook → Calendar.
# Usage: ./install-launchd.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
RUN_BOT="$ROOT/run-bot.sh"
CONFIG_FILE="$ROOT/config/schedule.env"
# LibCal day opens at midnight — land in the first few minutes.
SCHEDULE_HOUR="${SCHEDULE_HOUR:-0}"
JITTER_MINUTES="${SCHEDULE_JITTER_MINUTES:-8}"
BASE_MINUTE="${SCHEDULE_BASE_MINUTE:-$((1 + RANDOM % 4))}"  # :01–:04

# shellcheck source=scripts/launchd.sh
source "$ROOT/scripts/launchd.sh"

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: launchd scheduling is macOS only" >&2
  exit 1
fi

if [[ ! -x "$RUN_BOT" ]]; then
  echo "Missing $RUN_BOT"
  exit 1
fi

mkdir -p "$ROOT/config" "$ROOT/logs" "$HOME/Library/LaunchAgents"
cat > "$CONFIG_FILE" <<EOF
# Generated by install-launchd.sh — re-run to reshuffle.
SCHEDULE_BASE_MINUTE=${BASE_MINUTE}
SCHEDULE_BASE_HOUR=${SCHEDULE_HOUR}
SCHEDULE_JITTER_MINUTES=${JITTER_MINUTES}
TARGET_ROOM=360H
DAYS_AHEAD=3
AUTO_SCRAPE=1
EOF
chmod 600 "$CONFIG_FILE"

PLIST="$(launchd_plist_path)"
# launchd weekdays: 0=Sun, 1=Mon, ..., 5=Fri, 6=Sat
# Fri→Mon, Sat→Tue, Sun→Wed, Mon→Thu, Tue→Fri
WEEKDAYS=(5 6 0 1 2)

{
  cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${RUN_BOT}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${ROOT}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>SCHEDULED_RUN</key>
    <string>1</string>
    <key>TARGET_ROOM</key>
    <string>360H</string>
    <key>DAYS_AHEAD</key>
    <string>3</string>
    <key>AUTO_SCRAPE</key>
    <string>1</string>
    <key>CLOSE_AFTER_SECONDS</key>
    <string>5</string>
    <key>RUN_HEADLESS</key>
    <string>1</string>
    <key>OUTLOOK_SCRAPE_ACCOUNT</key>
    <string>Josh</string>
    <key>PATH</key>
    <string>${ROOT}/venv/bin:/usr/local/bin:/opt/homebrew/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>StartCalendarInterval</key>
  <array>
EOF
  for day in "${WEEKDAYS[@]}"; do
    cat <<EOF
    <dict>
      <key>Weekday</key>
      <integer>${day}</integer>
      <key>Hour</key>
      <integer>${SCHEDULE_HOUR}</integer>
      <key>Minute</key>
      <integer>${BASE_MINUTE}</integer>
    </dict>
EOF
  done
  cat <<EOF
  </array>
  <key>StandardOutPath</key>
  <string>${ROOT}/logs/launchd.out.log</string>
  <key>StandardErrorPath</key>
  <string>${ROOT}/logs/launchd.err.log</string>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
EOF
} > "$PLIST"

launchd_load "$PLIST"
remove_legacy_cron "$RUN_BOT" || true

# Also keep the Outlook scrape agent polling (backup if post-book scrape misses mail).
if [[ -x "$ROOT/scripts/install-outlook-scrape-launchd.sh" ]]; then
  "$ROOT/scripts/install-outlook-scrape-launchd.sh" || true
fi

end_min=$((BASE_MINUTE + JITTER_MINUTES))
end_hour=$SCHEDULE_HOUR
if (( end_min >= 60 )); then
  end_min=$((end_min % 60))
  end_hour=$((SCHEDULE_HOUR + 1))
fi

printf '\nInstalled LaunchAgent (weekday rooms only — no Sat/Sun bookings):\n'
printf '  %s\n' "$PLIST"
printf '\nSchedule: Fri→Mon, Sat→Tue, Sun→Wed, Mon→Thu, Tue→Fri\n'
printf 'Run window: ~%02d:%02d–%02d:%02d (random delay each night, up to %s min)\n' \
  "$SCHEDULE_HOUR" "$BASE_MINUTE" "$end_hour" "$end_min" "$JITTER_MINUTES"
printf 'Target: 360H preferred, 12pm–10pm, 3 accounts, DAYS_AHEAD=3\n'
printf 'After book: auto Outlook scrape → Google Calendar (also polls every 5 min)\n'
printf 'Config: %s\n' "$CONFIG_FILE"
printf 'Logs: %s/logs/study_room_bot.log\n' "$ROOT"
printf 'Launchd: %s/logs/launchd.out.log\n' "$ROOT"
printf '\nTest now (no jitter): ./run-bot.sh --now\n'
printf 'Remove: ./uninstall-launchd.sh\n'
printf 'Status: launchctl print %s\n' "$LAUNCHD_SERVICE"
