#!/usr/bin/env bash
# Install midnight study-room booking cron (Mon–Fri targets, 3 days ahead).
# Fires Fri–Tue right after midnight (when LibCal opens +3 days) with small jitter.
# Prefers 360H, rotates 3 accounts for 12pm–10pm, then scrapes Outlook → Calendar.
# Linux equivalent of ./install-launchd.sh
# Usage: ./install-cron.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
RUN_BOT="$ROOT/run-bot.sh"
CONFIG_FILE="$ROOT/config/schedule.env"
# LibCal day opens at midnight — land in the first few minutes.
SCHEDULE_HOUR="${SCHEDULE_HOUR:-0}"
JITTER_MINUTES="${SCHEDULE_JITTER_MINUTES:-8}"
BASE_MINUTE="${SCHEDULE_BASE_MINUTE:-$((1 + RANDOM % 4))}"  # :01–:04

# shellcheck source=scripts/cron.sh
source "$ROOT/scripts/cron.sh"

if [[ "$(uname -s)" == "Darwin" ]]; then
  echo "On macOS use ./install-launchd.sh instead (or continue for dual install)." >&2
fi

if [[ ! -x "$RUN_BOT" ]]; then
  echo "Missing $RUN_BOT"
  exit 1
fi

if ! command -v crontab >/dev/null 2>&1; then
  echo "error: crontab not found — install cron (e.g. apt install cron)" >&2
  exit 1
fi

mkdir -p "$ROOT/config" "$ROOT/logs"
cat > "$CONFIG_FILE" <<EOF
# Generated by install-cron.sh — re-run to reshuffle.
SCHEDULE_BASE_MINUTE=${BASE_MINUTE}
SCHEDULE_BASE_HOUR=${SCHEDULE_HOUR}
SCHEDULE_JITTER_MINUTES=${JITTER_MINUTES}
TARGET_ROOM=360H
DAYS_AHEAD=3
AUTO_SCRAPE=1
EOF
chmod 600 "$CONFIG_FILE"

# cron DOW: 0=Sun … 5=Fri, 6=Sat
# Fri→Mon, Sat→Tue, Sun→Wed, Mon→Thu, Tue→Fri
CRON_DOW="5,6,0,1,2"

# LibCal opens at Eastern midnight — force America/New_York so UTC hosts still fire correctly.
TZ_NAME="${BOOKING_TZ:-America/New_York}"

# Inline env matches LaunchAgent EnvironmentVariables.
BOOK_LINE="CRON_TZ=${TZ_NAME}
${BASE_MINUTE} ${SCHEDULE_HOUR} * * ${CRON_DOW} cd ${ROOT} && SCHEDULED_RUN=1 TARGET_ROOM=360H DAYS_AHEAD=3 AUTO_SCRAPE=1 CLOSE_AFTER_SECONDS=5 RUN_HEADLESS=1 OUTLOOK_SCRAPE_ACCOUNT=Josh TZ=${TZ_NAME} PATH=\"${ROOT}/venv/bin:/usr/local/bin:/usr/bin:/bin\" ${RUN_BOT} >>${ROOT}/logs/cron.out.log 2>>${ROOT}/logs/cron.err.log"

cron_install_block "$CRON_BOOK_TAG" "$BOOK_LINE"

# Also keep the Outlook scrape agent polling (backup if post-book scrape misses mail).
if [[ -x "$ROOT/scripts/install-outlook-scrape-cron.sh" ]]; then
  "$ROOT/scripts/install-outlook-scrape-cron.sh" || true
fi

end_min=$((BASE_MINUTE + JITTER_MINUTES))
end_hour=$SCHEDULE_HOUR
if (( end_min >= 60 )); then
  end_min=$((end_min % 60))
  end_hour=$((SCHEDULE_HOUR + 1))
fi

printf '\nInstalled cron (weekday rooms only — no Sat/Sun bookings):\n'
printf '  tag: #%s\n' "$CRON_BOOK_TAG"
printf '\nSchedule: Fri→Mon, Sat→Tue, Sun→Wed, Mon→Thu, Tue→Fri\n'
printf 'Timezone: %s (LibCal midnight)\n' "$TZ_NAME"
printf 'Run window: ~%02d:%02d–%02d:%02d %s (random delay each night, up to %s min)\n' \
  "$SCHEDULE_HOUR" "$BASE_MINUTE" "$end_hour" "$end_min" "$TZ_NAME" "$JITTER_MINUTES"
printf 'Target: 360H preferred, 12pm–10pm, 3 accounts, DAYS_AHEAD=3\n'
printf 'After book: auto Outlook scrape → Google Calendar (also polls every 5 min)\n'
printf 'Config: %s\n' "$CONFIG_FILE"
printf 'Logs: %s/logs/study_room_bot.log\n' "$ROOT"
printf 'Cron: %s/logs/cron.out.log\n' "$ROOT"
printf '\nTest now (no jitter): ./run-bot.sh --now\n'
printf 'Remove: ./uninstall-cron.sh\n'
printf 'Status: crontab -l | sed -n "/BEGIN %s/,/END %s/p"\n' "$CRON_BOOK_TAG" "$CRON_BOOK_TAG"
