#!/bin/bash
# Install weekday study-room booking cron (Mon–Fri targets, 3 days ahead).
# Fires once daily on Fri–Tue with a random start window so runs are not
# always at the same minute.
# Usage: ./install-cron.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RUN_BOT="$ROOT/run-bot.sh"
CONFIG_FILE="$ROOT/config/cron.env"

# Window: cron fires between 7:25–7:44, then run-bot sleeps 0–N more minutes.
CRON_HOUR="${CRON_HOUR:-7}"
JITTER_MINUTES="${CRON_JITTER_MINUTES:-50}"
BASE_MINUTE=$((25 + RANDOM % 20))

mkdir -p "$ROOT/config"
cat > "$CONFIG_FILE" <<EOF
# Generated by install-cron.sh — re-run ./install-cron.sh to reshuffle.
CRON_BASE_MINUTE=${BASE_MINUTE}
CRON_BASE_HOUR=${CRON_HOUR}
CRON_JITTER_MINUTES=${JITTER_MINUTES}
EOF
chmod 600 "$CONFIG_FILE"

CRON_SCHEDULE="${CRON_SCHEDULE:-$BASE_MINUTE $CRON_HOUR * * 5,6,0,1,2}"
CRON_LINE="$CRON_SCHEDULE SCHEDULED_RUN=1 CRON_JITTER_MINUTES=$JITTER_MINUTES $RUN_BOT"

if [[ ! -x "$RUN_BOT" ]]; then
  echo "Missing $RUN_BOT"
  exit 1
fi

TMP="$(mktemp)"
crontab -l 2>/dev/null | grep -v "$RUN_BOT" > "$TMP" || true
echo "$CRON_LINE" >> "$TMP"
crontab "$TMP"
rm -f "$TMP"

end_min=$((BASE_MINUTE + JITTER_MINUTES))
end_hour=$CRON_HOUR
if (( end_min >= 60 )); then
  end_min=$((end_min % 60))
  end_hour=$((CRON_HOUR + 1))
fi

printf '\nInstalled cron job (weekday rooms only — no Sat/Sun bookings):\n'
crontab -l | grep "$RUN_BOT"
printf '\nSchedule: Fri→Mon, Sat→Tue, Sun→Wed, Mon→Thu, Tue→Fri\n'
printf 'Run window: ~%02d:%02d–%02d:%02d (random delay each day, up to %s min)\n' \
  "$CRON_HOUR" "$BASE_MINUTE" "$end_hour" "$end_min" "$JITTER_MINUTES"
printf 'Config: %s\n' "$CONFIG_FILE"
printf 'Logs: %s/logs/study_room_bot.log\n' "$ROOT"
printf 'Errors: %s/logs/study_room_bot_error.log\n' "$ROOT"
printf '\nTest now (no jitter): SCHEDULED_RUN=0 %s\n' "$RUN_BOT"
printf 'Remove: %s/uninstall-cron.sh\n' "$ROOT"
