#!/bin/bash
# Install weekday study-room booking LaunchAgent (Mon–Fri targets, 3 days ahead).
# Fires once daily on Fri–Tue with a random morning window + daily jitter.
# Usage: ./install-launchd.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RUN_BOT="$ROOT/run-bot.sh"
CONFIG_FILE="$ROOT/config/schedule.env"
SCHEDULE_HOUR="${SCHEDULE_HOUR:-7}"
JITTER_MINUTES="${SCHEDULE_JITTER_MINUTES:-50}"
BASE_MINUTE=$((25 + RANDOM % 20))

# shellcheck source=scripts/launchd.sh
source "$ROOT/scripts/launchd.sh"

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "error: launchd scheduling is macOS only" >&2
  exit 1
fi

if [[ ! -x "$RUN_BOT" ]]; then
  echo "Missing $RUN_BOT"
  exit 1
fi

mkdir -p "$ROOT/config" "$ROOT/logs" "$HOME/Library/LaunchAgents"
cat > "$CONFIG_FILE" <<EOF
# Generated by install-launchd.sh — re-run to reshuffle.
SCHEDULE_BASE_MINUTE=${BASE_MINUTE}
SCHEDULE_BASE_HOUR=${SCHEDULE_HOUR}
SCHEDULE_JITTER_MINUTES=${JITTER_MINUTES}
EOF
chmod 600 "$CONFIG_FILE"

PLIST="$(launchd_plist_path)"
# launchd weekdays: 0=Sun, 1=Mon, ..., 5=Fri, 6=Sat
WEEKDAYS=(5 6 0 1 2)

{
  cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${LAUNCHD_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${RUN_BOT}</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${ROOT}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>SCHEDULED_RUN</key>
    <string>1</string>
    <key>PATH</key>
    <string>${ROOT}/venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>StartCalendarInterval</key>
  <array>
EOF
  for day in "${WEEKDAYS[@]}"; do
    cat <<EOF
    <dict>
      <key>Weekday</key>
      <integer>${day}</integer>
      <key>Hour</key>
      <integer>${SCHEDULE_HOUR}</integer>
      <key>Minute</key>
      <integer>${BASE_MINUTE}</integer>
    </dict>
EOF
  done
  cat <<EOF
  </array>
  <key>StandardOutPath</key>
  <string>${ROOT}/logs/launchd.out.log</string>
  <key>StandardErrorPath</key>
  <string>${ROOT}/logs/launchd.err.log</string>
  <key>RunAtLoad</key>
  <false/>
</dict>
</plist>
EOF
} > "$PLIST"

launchd_load "$PLIST"
remove_legacy_cron "$RUN_BOT" || true

end_min=$((BASE_MINUTE + JITTER_MINUTES))
end_hour=$SCHEDULE_HOUR
if (( end_min >= 60 )); then
  end_min=$((end_min % 60))
  end_hour=$((SCHEDULE_HOUR + 1))
fi

printf '\nInstalled LaunchAgent (weekday rooms only — no Sat/Sun bookings):\n'
printf '  %s\n' "$PLIST"
printf '\nSchedule: Fri→Mon, Sat→Tue, Sun→Wed, Mon→Thu, Tue→Fri\n'
printf 'Run window: ~%02d:%02d–%02d:%02d (random delay each day, up to %s min)\n' \
  "$SCHEDULE_HOUR" "$BASE_MINUTE" "$end_hour" "$end_min" "$JITTER_MINUTES"
printf 'Config: %s\n' "$CONFIG_FILE"
printf 'Logs: %s/logs/study_room_bot.log\n' "$ROOT"
printf 'Launchd: %s/logs/launchd.out.log\n' "$ROOT"
printf '\nTest now (no jitter): SCHEDULED_RUN=0 %s\n' "$RUN_BOT"
printf 'Remove: %s/uninstall-launchd.sh\n' "$ROOT"
printf 'Status: launchctl print %s\n' "$LAUNCHD_SERVICE"
